# Generated by Django 4.2.3 on 2023-07-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_address_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='price',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
